import type { AdminFeatureTab } from "@/lib/admin/types";

export const adminFeatureTabs: AdminFeatureTab[] = [
  {
    key: "home",
    label: "Trang chủ",
    description: "Tổng quan hệ thống quản trị và các thông báo quan trọng.",
    endpoints: [],
  },
  {
    key: "accounts",
    label: "Quản lý tài khoản",
    description: "Danh sách tài khoản, vai trò và trạng thái đăng nhập hệ thống.",
    endpoints: [
      { method: "GET", path: "/api/v1/accounts" },
      { method: "GET", path: "/api/v1/accounts/{id}" },
      { method: "POST", path: "/api/v1/accounts" },
      { method: "PUT", path: "/api/v1/accounts/{id}" },
      { method: "PATCH", path: "/api/v1/accounts/{id}/status" },
      { method: "PATCH", path: "/api/v1/accounts/{id}/reset-password" },
    ],
  },
  {
    key: "roles",
    label: "Vai trò và quyền",
    description: "Quản lý vai trò và tập quyền của hệ thống.",
    endpoints: [
      { method: "GET", path: "/api/v1/roles" },
      { method: "GET", path: "/api/v1/roles/{id}" },
      { method: "POST", path: "/api/v1/roles" },
      { method: "PUT", path: "/api/v1/roles/{id}" },
      { method: "DELETE", path: "/api/v1/roles/{id}" },
      { method: "GET", path: "/api/v1/roles/permissions" },
    ],
  },
  {
    key: "semesters",
    label: "Quản lý học kỳ",
    description: "Tạo học kỳ, thời gian học và tổng số tuần để mở đăng ký đúng kỳ.",
    endpoints: [
      { method: "GET", path: "/api/v1/semesters" },
      { method: "GET", path: "/api/v1/semesters/{id}" },
      { method: "POST", path: "/api/v1/semesters" },
      { method: "PUT", path: "/api/v1/semesters/{id}" },
      { method: "DELETE", path: "/api/v1/semesters/{id}" },
    ],
  },
  {
    key: "registration-periods",
    label: "Đợt đăng ký học phần",
    description: "Quản lý đợt đăng ký gắn với từng học kỳ và trạng thái mở đăng ký.",
    endpoints: [
      { method: "GET", path: "/api/v1/registration-periods" },
      { method: "GET", path: "/api/v1/registration-periods/{id}" },
      { method: "POST", path: "/api/v1/registration-periods" },
      { method: "PUT", path: "/api/v1/registration-periods/{id}" },
      { method: "DELETE", path: "/api/v1/registration-periods/{id}" },
    ],
  },
  {
    key: "faculties",
    label: "Quản lý khoa",
    description: "Quản lý danh sách khoa trong hệ thống.",
    endpoints: [{ method: "GET", path: "/api/v1/faculties" }],
  },
  {
    key: "majors",
    label: "Quản lý ngành",
    description: "Quản lý danh sách ngành đào tạo theo khoa.",
    endpoints: [
      { method: "GET", path: "/api/v1/majors" },
      { method: "GET", path: "/api/v1/majors/faculty/{facultyId}" },
    ],
  },
  {
    key: "specializations",
    label: "Quản lý chuyên ngành",
    description: "Quản lý chuyên ngành theo từng ngành đào tạo.",
    endpoints: [
      { method: "GET", path: "/api/v1/specializations" },
      { method: "GET", path: "/api/v1/specializations/major/{majorId}" },
    ],
  },
  {
    key: "cohorts",
    label: "Quản lý niên khóa",
    description: "Quản lý danh sách niên khóa đào tạo.",
    endpoints: [{ method: "GET", path: "/api/v1/cohorts" }],
  },
  {
    key: "courses",
    label: "Quản lý môn học",
    description: "Quản lý danh sách môn học trong chương trình đào tạo.",
    endpoints: [
      { method: "GET", path: "/api/v1/courses" },
      { method: "GET", path: "/api/v1/courses/faculty/{facultyId}" },
    ],
  },
  {
    key: "grade-components",
    label: "Cấu hình điểm",
    description: "Quản lý các thành phần điểm theo môn học.",
    endpoints: [
      { method: "GET", path: "/api/v1/grade-components" },
      { method: "POST", path: "/api/v1/grade-components" },
      { method: "GET", path: "/api/v1/courses/{courseId}/grade-components" },
    ],
  },
  {
    key: "classrooms",
    label: "Quản lý phòng học",
    description: "Quản lý danh sách phòng học và sức chứa.",
    endpoints: [{ method: "GET", path: "/api/v1/classrooms" }],
  },
  {
    key: "administrative-classes",
    label: "Quản lý lớp chủ nhiệm",
    description: "Quản lý lớp hành chính/lớp chủ nhiệm.",
    endpoints: [{ method: "GET", path: "/api/v1/administrative-classes" }],
  },
  {
    key: "students",
    label: "Quản lý sinh viên",
    description: "Theo dõi danh sách sinh viên trong hệ thống.",
    endpoints: [
      { method: "GET", path: "/api/v1/students" },
      { method: "PATCH", path: "/api/v1/students/{id}/status" },
    ],
  },
  {
    key: "lecturers",
    label: "Quản lý giảng viên",
    description: "Theo dõi danh sách giảng viên.",
    endpoints: [{ method: "GET", path: "/api/v1/lecturers" }],
  },
  {
    key: "guardians",
    label: "Quản lý phụ huynh",
    description: "Theo dõi danh sách phụ huynh.",
    endpoints: [{ method: "GET", path: "/api/v1/guardians" }],
  },
  {
    key: "course-sections",
    label: "Quản lý Lớp học phần",
    description:
      "Tạo lớp học phần theo môn và học kỳ, sau đó mở trạng thái cho đợt đăng ký.",
    endpoints: [
      { method: "GET", path: "/api/v1/course-sections" },
      { method: "GET", path: "/api/v1/course-sections/course/{courseId}" },
      { method: "GET", path: "/api/v1/course-sections/semester/{semesterId}" },
      { method: "POST", path: "/api/v1/course-sections" },
      { method: "PUT", path: "/api/v1/course-sections/{id}" },
      { method: "PATCH", path: "/api/v1/course-sections/{id}/status" },
      { method: "DELETE", path: "/api/v1/course-sections/{id}" },
    ],
  },
  {
    key: "recurring-schedules",
    label: "Quản lý Lịch học định kỳ",
    description:
      "Gắn lịch học định kỳ cho từng lớp học phần theo thứ, tiết và phạm vi tuần học.",
    endpoints: [
      { method: "GET", path: "/api/v1/recurring-schedules/section/{sectionId}" },
      { method: "GET", path: "/api/v1/recurring-schedules/{id}" },
      { method: "GET", path: "/api/v1/recurring-schedules/{id}/sessions" },
      { method: "POST", path: "/api/v1/recurring-schedules" },
      { method: "PUT", path: "/api/v1/recurring-schedules/{id}" },
      { method: "DELETE", path: "/api/v1/recurring-schedules/{id}" },
    ],
  },
  {
    key: "grade-management",
    label: "Quản lý điểm",
    description: "Xem bảng điểm theo lớp học phần và cập nhật phiếu điểm.",
    endpoints: [
      { method: "GET", path: "/api/v1/course-sections/{sectionId}/grade-reports" },
      { method: "GET", path: "/api/v1/students/{studentId}/grade-reports" },
      { method: "POST", path: "/api/v1/grade-reports" },
      { method: "GET", path: "/api/v1/grade-reports/{id}" },
      { method: "PUT", path: "/api/v1/grade-reports/{id}" },
      { method: "DELETE", path: "/api/v1/grade-reports/{id}" },
    ],
  },
  {
    key: "attendance-management",
    label: "Quản lý điểm danh",
    description:
      "Theo dõi và hiệu chỉnh điểm danh theo lớp học phần, lịch học định kỳ và từng buổi học.",
    endpoints: [
      { method: "GET", path: "/api/v1/course-sections" },
      { method: "GET", path: "/api/v1/recurring-schedules/section/{sectionId}" },
      { method: "GET", path: "/api/v1/recurring-schedules/{id}/sessions" },
      { method: "GET", path: "/api/v1/class-sessions/{sessionId}/attendances" },
      { method: "PUT", path: "/api/v1/attendances/{id}" },
      { method: "DELETE", path: "/api/v1/attendances/{id}" },
    ],
  },
  {
    key: "admissions",
    label: "Tuyển sinh",
    description: "Lọc và xét duyệt hồ sơ tuyển sinh.",
    endpoints: [
      { method: "GET", path: "/api/v1/admin/admissions/config/periods" },
      { method: "GET", path: "/api/v1/admin/admissions/config/periods/{id}" },
      { method: "POST", path: "/api/v1/admin/admissions/config/periods/campaign" },
      { method: "PUT", path: "/api/v1/admin/admissions/config/periods/{id}" },
      { method: "DELETE", path: "/api/v1/admin/admissions/config/periods/{id}" },
      { method: "GET", path: "/api/v1/admin/admissions/config/blocks" },
      { method: "POST", path: "/api/v1/admin/admissions/config/blocks" },
      { method: "PUT", path: "/api/v1/admin/admissions/config/blocks/{id}" },
      { method: "DELETE", path: "/api/v1/admin/admissions/config/blocks/{id}" },
      { method: "GET", path: "/api/v1/admin/admissions/config/benchmarks" },
      { method: "POST", path: "/api/v1/admin/admissions/config/benchmarks/bulk" },
      { method: "PUT", path: "/api/v1/admin/admissions/config/benchmarks/{id}" },
      { method: "DELETE", path: "/api/v1/admin/admissions/config/benchmarks/{id}" },
      { method: "GET", path: "/api/v1/admin/admissions/config/form-options" },
      { method: "GET", path: "/api/v1/admin/admissions/applications" },
      { method: "GET", path: "/api/v1/admin/admissions/applications/{id}" },
      { method: "PATCH", path: "/api/v1/admin/admissions/applications/{id}/review" },
      { method: "POST", path: "/api/v1/admin/admissions/applications/bulk-review" },
      { method: "POST", path: "/api/v1/admin/admissions/applications/auto-screen/{periodId}" },
    ],
  },
  {
    key: "admissions-onboarding",
    label: "Chốt nhập học",
    description: "Chuyển hồ sơ đã duyệt sang nhập học và sinh tài khoản/hồ sơ liên quan.",
    endpoints: [
      { method: "GET", path: "/api/v1/admin/admissions/config/form-options" },
      { method: "GET", path: "/api/v1/admin/admissions/applications" },
      { method: "POST", path: "/api/v1/admin/admissions/applications/onboard/{periodId}" },
      { method: "GET", path: "/api/v1/roles" },
      { method: "GET", path: "/api/v1/cohorts" },
      { method: "GET", path: "/api/v1/administrative-classes" },
      { method: "GET", path: "/api/v1/accounts" },
      { method: "GET", path: "/api/v1/students" },
      { method: "GET", path: "/api/v1/guardians" },
    ],
  },
];

export const adminTopHeaderTabs = ["Quản trị hệ thống", "Báo cáo", "Cấu hình"] as const;
